lsi: false
safe: true
source: ./
incremental: false
markdown: GFM
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
header_pages:
  - brief_reviews/brief_reviews.md
  - reviews/reviews.md
  - fiction_fragments/fiction_fragments.md
