lsi: false
safe: true
source: ./
incremental: false
markdown: GFM
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
minima:
  skin: dark
author:
  name: James Marshall
  email: "marshall.james.c+attnpd@gmail.com"
